language: php

dist: xenial

services:
  - mysql

env:
  global:
    - COMPOSER_ROOT_VERSION=1.9.x-dev

matrix:
  include:
    - php: '7.1'
      env: DB=MYSQL CORE_RELEASE=3.7
    - php: '7.2'
      env: DB=MYSQL CORE_RELEASE=3.7
    - php: '7.3'
      env: DB=MYSQL CORE_RELEASE=3.7

before_script:
  - composer self-update || true
  - git clone git://github.com/silverstripe/silverstripe-travis-support.git ~/travis-support
  - php ~/travis-support/travis_setup.php --source `pwd` --target ~/builds/ss --require cwp/starter-theme:1.x-dev --require symbiote/silverstripe-advancedworkflow:^4 --require silverstripe/userforms:^4
  - cd ~/builds/ss

script:
  - vendor/bin/phpunit cwp/tests
